# Ödev 1: 
Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [1]:
import numpy as np

In [6]:
array = np.array([1,2,3,4,5], dtype="int")

In [12]:
print(array)

[1 2 3 4 5]


In [13]:
print(array.ndim)

1


In [14]:
print(array.size)

5


# Ödev 2: 
Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [16]:
array = np.array([[1,2,6,7],[4,3,9,5]])
print(array)

[[1 2 6 7]
 [4 3 9 5]]


In [19]:
print(array.ndim)

2


In [21]:
print(array.size)

8


In [24]:
array[0,]

array([1, 2, 6, 7])

In [25]:
array[0,2]

6

In [47]:
np.shape(array)

(2, 4)

In [18]:
array2 = np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
print(array2)

[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]


In [20]:
print(array2.ndim)

3


In [22]:
print(array2.size)

12


In [30]:
array2[0,1]

array([21,  8, 11])

In [31]:
array2[0,1,2]

11

In [48]:
np.shape(array2)

(2, 2, 3)

# Ödev 3: 
İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [32]:
array

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [33]:
# İki boyutlu arraydaki 2 elemanına ulaşalım
array[0,1]

2

In [35]:
# İki boyutlu arraydaki 7 elemanına ulaşalım
array[0,3]

7

In [36]:
array2

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [37]:
# Üç boyutlu arraydaki 9 elemanına ulaşalım
array2[1,1,2]

9

In [39]:
# Üç boyutlu arraydaki 5 elemanına ulaşalım
array2[0,0,1]

5

# Ödev 4 
Arrayler üzerinde slicing işlemi uygulayalım.

In [40]:
array

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [41]:
# İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
array[0,1:3]

array([2, 6])

In [42]:
# İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
array[1,1:]

array([3, 9, 5])

In [43]:
array2

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [45]:
# Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
array2[0,1,:]

array([21,  8, 11])

In [46]:
# Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
array2[1,0,1:]

array([ 6, 20])

# Ödev 5: 
5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [51]:
sıfırlar = np.zeros((5,3),dtype="int")
birler = np.ones((5,3),dtype="int")

print(sıfırlar)
print(birler)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [53]:
satir = np.concatenate([sıfırlar, birler])
print(satir)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [55]:
sutun = np.concatenate([sıfırlar, birler], axis=1)
print(sutun)

[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
